--MODULO2, SEMANA 7, AULA 3 (SELECT)


SELECT * FROM USUARIOS;
SELECT * FROM USUARIOS WHERE NOME = 'Antônio';

SELECT * FROM USUARIOS WHERE NOME = 'Antônio' AND SOBRENOME = 'Reis';
SELECT * FROM USUARIOS WHERE NOME = 'Antônio' AND SOBRENOME = 'Oliveira';

SELECT * FROM USUARIOS WHERE NOME = 'Antônio' OR SOBRENOME = 'Oliveira';
SELECT * FROM USUARIOS WHERE NOME = 'Antônio' OR SOBRENOME = 'Mendes de Oliveira';

INSERT INTO USUARIOS (nome, sobrenome, data_nascimento, data_criacao, cpf) 
VALUES ('George', 'Bravo', '28/04/1984', '15/03/2023 19:35:10', '111.222.333-44');
INSERT INTO USUARIOS (nome, sobrenome, data_nascimento, data_criacao, cpf) 
VALUES ('Rodolfo', 'Rodrigues', '03/04/1989', '15/03/2023 19:35:10', '111.222.333-44');
INSERT INTO USUARIOS (nome, sobrenome, data_nascimento, data_criacao, cpf) 
VALUES ('Gustavo', 'Maia', '26/03/1983', '15/03/2023 19:35:10', '111.222.333-44');
COMMIT;


SELECT * FROM USUARIOS WHERE SOBRENOME LIKE '%de%';
SELECT * FROM USUARIOS WHERE NOME LIKE '%r%';
SELECT * FROM USUARIOS WHERE LOWER(NOME) LIKE '%r%';

SELECT UPPER(NOME), UPPER(SOBRENOME), LOWER(NOME), LOWER(SOBRENOME) FROM USUARIOS;

SELECT * FROM USUARIOS WHERE NOME LIKE 'G%';
SELECT * FROM USUARIOS WHERE NOME LIKE '%o';

SELECT * FROM USUARIOS WHERE NOME LIKE '_o';
SELECT * FROM USUARIOS WHERE NOME LIKE 'Jo_o';
SELECT * FROM USUARIOS WHERE NOME LIKE 'Jo__';
SELECT * FROM USUARIOS WHERE NOME LIKE '_o%';
SELECT * FROM USUARIOS WHERE SOBRENOME LIKE '%es%';

SELECT * FROM USUARIOS WHERE NOME NOT LIKE 'Jo_o';

INSERT INTO POSTAGENS (CONTEUDO, TITULO, DATA_CRIACAO, DATA_ATUALIZACAO, NUMERO_REACOES, ID_USUARIO_CRIADOR)
VALUES ('TEXTO', 'TITULO', '15/03/2023', '15/03/2023', 0, 21);
COMMIT;

INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, DATA_REACAO, TIPO)
VALUES (21, 22, SYSDATE, 'CURTIDA');
INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, DATA_REACAO, TIPO)
VALUES (21, 23, SYSDATE, 'AMEI');
INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, DATA_REACAO, TIPO)
VALUES (21, 1, SYSDATE, 'RISADA');
INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, DATA_REACAO, TIPO)
VALUES (21, 4, SYSDATE, 'CURTIDA');
COMMIT;


SELECT * FROM REACOES WHERE ID_POSTAGEM = 21 AND TIPO IN ('CURTIDA', 'AMEI', 'RISADA', 'NOJO', 'APOIO', 'APLAUSO');
SELECT * FROM REACOES WHERE ID_POSTAGEM = 21 AND (TIPO = 'CURTIDA' OR TIPO = 'AMEI' OR TIPO = 'RISADA' OR TIPO = 'NOJO' OR TIPO = 'APOIO' OR TIPO = 'APLAUSO');
SELECT * FROM REACOES WHERE ID_POSTAGEM = 21 AND TIPO NOT IN ('CURTIDA', 'AMEI');

SELECT * FROM USUARIOS WHERE DATA_NASCIMENTO BETWEEN '01/01/1980' AND '31/12/1989';
SELECT * FROM USUARIOS WHERE DATA_NASCIMENTO >= '01/01/1980' AND DATA_NASCIMENTO <= '31/12/1989';
SELECT * FROM USUARIOS WHERE DATA_NASCIMENTO NOT BETWEEN '01/01/1980' AND '31/12/1989';

ALTER TABLE USUARIOS ADD RG VARCHAR2(10);

UPDATE USUARIOS SET RG = '12345' WHERE ID = 1;
UPDATE USUARIOS SET RG = '67890' WHERE ID = 21;
COMMIT;

SELECT * FROM USUARIOS WHERE RG IS NULL;
SELECT * FROM USUARIOS WHERE RG IS NOT NULL;
SELECT * FROM USUARIOS WHERE RG = '';

UPDATE USUARIOS SET RG = '' WHERE ID = 4;

UPDATE postagens P SET numero_reacoes = 4 WHERE P.id_usuario_criador = 21;
COMMIT;

SELECT * FROM POSTAGENS WHERE numero_reacoes > 3;
SELECT * FROM POSTAGENS WHERE NUMERO_REACOES < 1;
SELECT * FROM REACOES WHERE TIPO <> 'CURTIDA';
SELECT * FROM POSTAGENS WHERE NUMERO_REACOES >= 4;

SELECT TIPO, ID_USUARIO_REATOR FROM REACOES WHERE TIPO <> 'CURTIDA';

SELECT TIPO AS T, ID_USUARIO_REATOR AS REATOR FROM REACOES R WHERE R.TIPO <> 'CURTIDA';

ALTER TABLE USUARIOS MODIFY DATA_CRIACAO DEFAULT SYSDATE;

INSERT INTO USUARIOS (NOME, SOBRENOME, DATA_NASCIMENTO, CPF) 
VALUES ('João', 'Alves', '25/02/1991', '123');
COMMIT;

SELECT * FROM POSTAGENS ORDER BY NUMERO_REACOES; --ASC
SELECT * FROM POSTAGENS ORDER BY NUMERO_REACOES DESC;

SELECT * FROM USUARIOS ORDER BY DATA_NASCIMENTO DESC, NOME, SOBRENOME;

SELECT DATA_NASCIMENTO FROM USUARIOS GROUP BY DATA_NASCIMENTO;
SELECT DATA_NASCIMENTO, NOME FROM USUARIOS GROUP BY DATA_NASCIMENTO, NOME;

SELECT COUNT(*) FROM USUARIOS;
SELECT COUNT(*) FROM REACOES WHERE TIPO = 'CURTIDA';
SELECT COUNT(*) AS TOTAL, TIPO FROM REACOES GROUP BY TIPO;

ALTER TABLE POSTAGENS MODIFY DATA_CRIACAO DEFAULT SYSDATE;
ALTER TABLE POSTAGENS MODIFY DATA_ATUALIZACAO DEFAULT SYSDATE;
INSERT INTO POSTAGENS (CONTEUDO, TITULO, NUMERO_REACOES, ID_USUARIO_CRIADOR) 
VALUES ('CONTEUDO DA POSTAGEM', 'TITULO DA POSTAGEM', '2', 1);

ALTER TABLE REACOES MODIFY DATA_REACAO DEFAULT SYSDATE;
INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, TIPO) 
VALUES (22, 24, 'RISADA');
INSERT INTO REACOES (ID_POSTAGEM, ID_USUARIO_REATOR, TIPO) 
VALUES (22, 4, 'AMEI');
COMMIT;

SELECT AVG(NUMERO_REACOES) AS QTD_MEDIA_REACOES_POR_POSTAGEM FROM postagens;

SELECT AVG(NUMERO_REACOES) AS QTD_MEDIA_REACOES, ID_USUARIO_CRIADOR AS USUARIO
FROM POSTAGENS 
GROUP BY ID_USUARIO_CRIADOR;


SELECT SUM(NUMERO_REACOES) AS TOTAL_REACOES FROM POSTAGENS;

SELECT SUM(NUMERO_REACOES) AS TOTAL_REACOES, ID_USUARIO_CRIADOR AS USUARIO
FROM POSTAGENS
GROUP BY ID_USUARIO_CRIADOR;

INSERT INTO POSTAGENS (CONTEUDO, TITULO, NUMERO_REACOES, ID_USUARIO_CRIADOR) 
VALUES ('CONTEUDO DA POSTAGEM', 'TITULO DA POSTAGEM', 5, 1);
INSERT INTO POSTAGENS (CONTEUDO, TITULO, NUMERO_REACOES, ID_USUARIO_CRIADOR) 
VALUES ('CONTEUDO DA POSTAGEM', 'TITULO DA POSTAGEM', 3, 1);
INSERT INTO POSTAGENS (CONTEUDO, TITULO, NUMERO_REACOES, ID_USUARIO_CRIADOR) 
VALUES ('CONTEUDO DA POSTAGEM', 'TITULO DA POSTAGEM', 8, 21);
INSERT INTO POSTAGENS (CONTEUDO, TITULO, NUMERO_REACOES, ID_USUARIO_CRIADOR) 
VALUES ('CONTEUDO DA POSTAGEM', 'TITULO DA POSTAGEM', 12, 21);
COMMIT;

SELECT MAX(NUMERO_REACOES) FROM POSTAGENS;

SELECT MAX(NUMERO_REACOES), ID_USUARIO_CRIADOR FROM POSTAGENS
GROUP BY ID_USUARIO_CRIADOR;

SELECT MIN(NUMERO_REACOES) FROM POSTAGENS;

SELECT MIN(NUMERO_REACOES), ID_USUARIO_CRIADOR FROM POSTAGENS
GROUP BY ID_USUARIO_CRIADOR;

SELECT SUM(NUMERO_REACOES) AS TOTAL_REACOES, ID_USUARIO_CRIADOR AS USUARIO
FROM POSTAGENS
GROUP BY ID_USUARIO_CRIADOR
HAVING SUM(NUMERO_REACOES) > 20;

SELECT DISTINCT DATA_NASCIMENTO FROM USUARIOS;
SELECT DISTINCT TITULO FROM POSTAGENS;
SELECT DISTINCT NOME FROM USUARIOS ORDER BY NOME;

CREATE TABLE ALUNOS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR2(128) NOT NULL,
    SOBRENOME VARCHAR2(128) NOT NULL,
    MEDIA NUMBER(4,2),
    PRIMARY KEY(ID)
);

INSERT INTO ALUNOS (NOME, SOBRENOME, MEDIA)
VALUES ('Lucas', 'Reis', 7);
INSERT INTO ALUNOS (NOME, SOBRENOME, MEDIA)
VALUES ('Pedro', 'Lima', 8.00);
INSERT INTO ALUNOS (NOME, SOBRENOME, MEDIA)
VALUES ('Jonathan', 'Spinelli', 7.5);
INSERT INTO ALUNOS (NOME, SOBRENOME, MEDIA)
VALUES ('André', 'Hopf', 8.5);
INSERT INTO ALUNOS (NOME, SOBRENOME, MEDIA)
VALUES ('Matheus', 'Espindola', 7.3);
commit;

SELECT *
FROM ALUNOS 
WHERE MEDIA > (SELECT MEDIA FROM ALUNOS WHERE ID = 2);
