--MODULO2, SEMANA7, AULA4 - STREAMING DE MUSICA (DML)

-- USUARIOS
INSERT INTO USUARIOS_STREAMING (NOME, SOBRENOME, DATA_NASCIMENTO)
VALUES ('Leonardo', 'Fonseca', '20/03/1990');
INSERT INTO USUARIOS_STREAMING (NOME, SOBRENOME, DATA_NASCIMENTO)
VALUES ('Halan', 'Germano', '10/04/1992');
INSERT INTO USUARIOS_STREAMING (NOME, SOBRENOME, DATA_NASCIMENTO)
VALUES ('Jaime', 'Leal', '15/01/1985');
INSERT INTO USUARIOS_STREAMING (NOME, SOBRENOME, DATA_NASCIMENTO, ADMINISTRADOR)
VALUES ('João Vitor', 'Fraga', '30/10/1991', '1');
COMMIT;

--PLAYLISTS
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('FESTA', 1);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('TRABALHO', 1);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('FOCO', 2);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('ACADEMIA', 3);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('CHURRASCO', 3);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('FOCO', 3);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('ACADEMIA', 2);
INSERT INTO PLAYLISTS (NOME, ID_USUARIO)
VALUES ('CHURRASCO', 2);
COMMIT;

--GENEROS
INSERT INTO GENEROS(NOME) 
VALUES('SAMBA');
INSERT INTO GENEROS(NOME) 
VALUES('ROCK');
INSERT INTO GENEROS(NOME) 
VALUES('METAL');
INSERT INTO GENEROS(NOME) 
VALUES('PAGODINHO');
INSERT INTO GENEROS(NOME) 
VALUES('SERTANEJO');
INSERT INTO GENEROS(NOME) 
VALUES('REGGAE');
COMMIT;

--ARTISTAS
INSERT INTO ARTISTAS(NOME, NACIONALIDADE) 
VALUES ('PARKWAY DRIVE', 'AUSTRALIA');
INSERT INTO ARTISTAS(NOME, NACIONALIDADE) 
VALUES ('DEMONIOS DA GAROA', 'BRASIL');
INSERT INTO ARTISTAS(NOME, NACIONALIDADE) 
VALUES ('SEPULTURA', 'BRASIL');
INSERT INTO ARTISTAS(NOME, NACIONALIDADE) 
VALUES ('CHITAOZINHO E XORORO', 'BRASIL');
INSERT INTO ARTISTAS(NOME, NACIONALIDADE) 
VALUES ('DAZARANHA', 'BRASIL');
COMMIT;

--ALBUNS
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('HORIZONS', 1);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('ATLAS', 1);

INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('HORIZONS', 1);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('ATLAS', 1);

INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('DEMONIOS DA GAROA', 2);

INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('ROOTS', 3);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('ARISE', 3);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('QUADRA', 3);

INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('Aqui O Sistema É Bruto', 4);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('A História Continua (Ao Vivo)', 4);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('Tom do Sertão', 4);

INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('Seja Bem Vindo', 5);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('Tribo da Lua', 5);
INSERT INTO ALBUNS (TITULO, ID_ARTISTA) 
VALUES ('Nossa Barulheira', 5);
COMMIT;

--MUSICAS
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Home is for the Heartless', 1, 3);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Romance is Dead', 1, 3);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Trem das Onze', 2, 1);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Saudosa Maloca', 2, 1);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Roots Bloody Roots', 3, 3);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Attitude', 3, 3);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Evidências', 4, 5);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Pense em Mim', 4, 5);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Tribo da Lua', 5, 6);
INSERT INTO MUSICAS(TITULO, ID_ARTISTA, ID_GENERO) 
VALUES('Salão de Festa a Vapor', 5, 6);
COMMIT;

--MUSICAS_PLAYLISTS