--MODULO2, SEMANA 7, AULA 4 (JOIN)

SELECT TIPO FROM REACOES WHERE NOME_USUARIO_REATOR = 'Antônio'; --ERRO

SELECT R.TIPO 
FROM REACOES R
JOIN USUARIOS U ON R.ID_USUARIO_REATOR = U.ID
WHERE U.NOME = 'Antônio';

SELECT U.NOME, U.SOBRENOME, P.TITULO
FROM USUARIOS U
LEFT JOIN POSTAGENS P
ON U.ID = P.ID_USUARIO_CRIADOR;

SELECT * 
FROM REACOES R
RIGHT JOIN POSTAGENS P
ON R.ID_POSTAGEM = P.ID;

SELECT *
FROM POSTAGENS P
FULL JOIN USUARIOS U
ON P.ID_USUARIO_CRIADOR = U.ID;