--MODULO2, SEMANA7, AULA4 - STREAMING DE MUSICA (SELECTs)

-- Artistas do gênero “samba”
SELECT A.NOME AS NOME_ARTISTA
FROM ARTISTAS A
JOIN generos_artistas GA
ON GA.id_artista = A.ID
JOIN GENEROS G
ON G.ID = ga.id_genero
WHERE G.NOME = 'SAMBA';

-- Albuns do gênero “METAL”
SELECT A.TITULO AS TITULO_ALBUM
FROM ALBUNS A
JOIN GENEROS_ALBUNS GA
ON GA.ID_ALBUM = A.ID
JOIN GENEROS G
ON G.ID = GA.ID_GENERO
WHERE G.NOME = 'METAL';

-- Dados de artista, álbum, duração e ano de lançamento de uma música.
SELECT M.TITULO AS TITULO_MUSICA, AR.NOME AS NOME_ARTISTA, 
       AL.TITULO AS TITULO_ALBUM, M.DURACAO_SEGUNDOS AS DURACAO_MUSICA, 
       M.DATA_LANCAMENTO AS LANCAMENTO_MUSICA 
FROM   MUSICAS M
JOIN   ARTISTAS AR
ON     AR.ID = M.ID_ARTISTA
JOIN   ALBUNS_MUSICAS AM
ON     AM.ID_MUSICA = M.ID
JOIN   ALBUNS AL
ON     AL.ID = AM.ID_ALBUM
WHERE  M.TITULO = 'Tribo da Lua';

-- Últimas 3 músicas reproduzidas por um determinado usuário.
SELECT *
  FROM REPRODUCOES R
  JOIN MUSICAS M ON R.ID_MUSICA = M.ID
  JOIN USUARIOS_STREAMING U ON R.ID_USUARIO = U.ID
 WHERE U.NOME = 'Halan'
 ORDER BY R.DATA_REPRODUCAO DESC
 FETCH FIRST 3 ROWS ONLY;

